CREATE TABLE `casestudies` (
`caseStudyId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`title` VARCHAR(255)  NULL,
`slug` VARCHAR(255)  NULL,
`clientName` VARCHAR(150)  NULL,
`industry` VARCHAR(150)  NULL,
`summary` VARCHAR(1000)  NULL,
`challenges` VARCHAR(1000)  NULL,
`solution` VARCHAR(1000)  NULL,
`results` VARCHAR(1000)  NULL,
`content` VARCHAR(5000)  NULL,
`authorId` INT  NOT NULL,
`isPublished` BOOLEAN  NOT NULL,
`publishedAt` TIMESTAMP  NULL,
`casestudyCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`casestudyUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`casestudyIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`authorId`) REFERENCES `users`(`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;