CREATE TABLE `clients` (
`clientId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100)  NOT NULL,
`logo` VARCHAR(255)  NULL,
`companyType` VARCHAR(255)  NULL,
`status` ENUM('active', 'inactive')  NOT NULL,
`clientCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`clientUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`clientIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;