CREATE TABLE `contacts` (
`contactId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`fullName` VARCHAR(150)  NOT NULL,
`email` VARCHAR(150)  NOT NULL,
`phone` VARCHAR(50)  NOT NULL,
`subject` VARCHAR(200)  NOT NULL,
`message` VARCHAR(5000)  NOT NULL,
`source` VARCHAR(100)  NOT NULL,
`ipAddress` VARCHAR(45)  NOT NULL,
`userAgent` VARCHAR(500)  NOT NULL,
`isRead` BOOLEAN  NOT NULL,
`receivedAt` TIMESTAMP  NULL,
`contactCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`contactUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`contactIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;