CREATE TABLE `eventCategories` (
`categoryId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100)  UNIQUE NOT NULL,
`description` TEXT  NULL,
`status` ENUM('active', 'inactive')  NOT NULL,
`eventCategoryCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`eventCategoryUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`eventCategoryIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;