CREATE TABLE `jobposts` (
`jobId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`jobTitle` VARCHAR(255)  NULL,
`department` VARCHAR(255)  NULL,
`location` VARCHAR(255)  NULL,
`jobType` ENUM('Full')  NOT NULL,
`salaryRange` VARCHAR(100)  NULL,
`requirements` VARCHAR(2000)  NULL,
`responsibilities` VARCHAR(2000)  NULL,
`benefits` VARCHAR(1000)  NULL,
`isActive` BOOLEAN  NOT NULL,
`postedBy` INT  NOT NULL,
`postedAt` TIMESTAMP  NULL,
`jobpostCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`jobpostUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`jobpostIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`postedBy`) REFERENCES `users`(`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;