CREATE TABLE `licenses` (
`id` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`licenseKey` VARCHAR(255)  NOT NULL,
`liveDomain` VARCHAR(255)  NULL,
`localDomain` VARCHAR(255)  NULL,
`expiresAt` TIMESTAMP  NULL,
`status` ENUM('active', 'expired', 'revoked')  NOT NULL,
`licenseCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`licenseUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`licenseIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;