CREATE TABLE `products` (
`productId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`productName` VARCHAR(255)  NULL,
`productPrice` DECIMAL  NULL,
`productImage` VARCHAR(255)  NOT NULL,
`productCategory` ENUM('digital', 'physical')  NOT NULL,
`productCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`productUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`productIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;