CREATE TABLE `serviceTypes` (
`id` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR(500)  NULL,
`description` VARCHAR(5000)  NULL,
`serviceTypeCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`serviceTypeUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`serviceTypeIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;