CREATE TABLE `servicepackages` (
`id` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`serviceTypeId` INT  NOT NULL,
`name` VARCHAR(100)  NULL,
`description` VARCHAR(5000)  NULL,
`price` BOOLEAN  NOT NULL,
`features` VARCHAR(1000)  NULL,
`isActive` BOOLEAN  NULL,
`servicepackageCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`servicepackageUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`servicepackageIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`serviceTypeId`) REFERENCES `servicetypes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;