CREATE TABLE `testimonials` (
`testimonialId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`clientId` INT  NOT NULL,
`name` VARCHAR(100)  NOT NULL,
`message` TEXT  NOT NULL,
`photo` VARCHAR(255)  NULL,
`designation` VARCHAR(100)  NULL,
`testimonialCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`testimonialUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`testimonialIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`clientId`) REFERENCES `clients`(`clientId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;