CREATE TABLE `tests` (
`testId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`testString` VARCHAR(250)  NOT NULL,
`testTimestamp` TIMESTAMP  NULL,
`testEnum` ENUM('value1', '')  NOT NULL,
`testBoolean` BOOLEAN  NOT NULL,
`testFloat` FLOAT(10,2)  NOT NULL,
`testDecimal` DECIMAL(10,2)  NOT NULL,
`testDouble` DOUBLE(10,2)  NOT NULL,
`testJSON` JSON  NULL,
`testFile` VARCHAR(255)  NOT NULL,
`testForeignKey` INT  NOT NULL,
`testCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`testUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`testIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`testForeignKey`) REFERENCES `users`(`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;